### PR TITLE
Remove the serifs

### PR DESCRIPTION
**Pull request by eigilhs**

### CODE REVIEW

**Review by mandus — APPROVED** [review]
*l*gtm

**Comment by alexanfl** [comment]
Do you regret not committing "I shot the serif"?

**Comment by eigilhs** [comment]
> Do you regret not committing "I shot the serif"?

I said that to @mandus the moment after committing :smile:

**Comment by eigilhs** [comment]
I regret it even more now that I see I didn't update the commit message when I removed the font size change.

**Pull request merged**
