### PR TITLE
Also compress the images in projects and services pages

### PR DESCRIPTION
**Pull request by FredrikMeyer**
Forgot to resize these as well in my previous PR.

### CODE REVIEW

**Comment by eigilhs** [comment]
Maybe 200px is a little small for these? Now they are > 1000px in my setup.

**Comment by FredrikMeyer** [comment]
> Maybe 200px is a little small for these? Now they are > 1000px in my setup.

@eigilhs How big is your monitor?? On my screen they render as ~150px in full screen view. Maybe 400px is better?

**Comment by eigilhs** [comment]
> > Maybe 200px is a little small for these? Now they are > 1000px in my setup.
> 
> @eigilhs How big is your monitor?? On my screen they render as ~150px in full screen view. Maybe 400px is better?

Sorry, I misunderstood which pictures were being resized :sweat_smile: I thought it was the service pictures. But the person images render to 267px on my screen (4K).

**Comment by FredrikMeyer** [comment]
> > > Maybe 200px is a little small for these? Now they are > 1000px in my setup.
> > 
> > 
> > @eigilhs How big is your monitor?? On my screen they render as ~150px in full screen view. Maybe 400px is better?
> 
> Sorry, I misunderstood which pictures were being resized 😅 I thought it was the service pictures. But the person images render to 267px on my screen (4K).

Okay, then 400px is probably okay, I think?

**Pull request merged**
